import React, { useMemo } from 'react';
import { motion } from 'framer-motion';
import { AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';
import { Info, AlertCircle, TrendingUp, Pill, Timer, Lightbulb, ChevronRight, Share2, CheckCircle2, ShieldAlert, Activity, BrainCircuit } from 'lucide-react';
import { cn } from '../../utils/cn';
import { useMeds } from '../../context/MedicationContext';

const PatientInsights: React.FC = () => {
  const { aiInsights, isLoading, adherenceHistory } = useMeds();

  // Inside PatientInsights.tsx

// PatientInsights.tsx (inside useMemo)

const trendData = useMemo(() => {
  const days = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
  const today = new Date();
  
  return Array.from({ length: 7 }, (_, i) => {
    const d = new Date();
    d.setDate(today.getDate() - (6 - i));
    const dateStr = d.toLocaleDateString('en-CA'); 

    const dayLogs = adherenceHistory?.filter(log => log.dateString === dateStr) || [];
    
    if (dayLogs.length === 0) return { day: days[d.getDay()], rate: 0 };

    // 1. ✅ ADD LATENCY PENALTIES: Ensures 8h delays show as 0% on the graph
    const dayPoints = dayLogs.reduce((acc, log) => {
      const lat = log.latencyMinutes || 0;
      if (log.status === 'missed' || lat >= 480) return acc + 0;
      if (lat > 60) return acc + 0.5;
      return acc + 1;
    }, 0);

    let score = Math.round((dayPoints / dayLogs.length) * 100);

    // 2. Toxicity Check (Already mostly correct, synced for safety)
    const timestamps = dayLogs.map(l => new Date(l.timestamp).getTime());
    let dayToxicity = false;
    dayLogs.forEach(log => {
      const sameTimeCount = timestamps.filter(t => 
        Math.abs(t - new Date(log.timestamp).getTime()) < 10 * 60 * 1000
      ).length;
      if (sameTimeCount >= 4) dayToxicity = true;
    });

    if (dayToxicity) score = Math.min(score, 35);

    return { day: days[d.getDay()], rate: score };
  });
}, [adherenceHistory]);


  // 2. UI Helper Functions (Ensure these are defined!)
  const getRiskStyles = (level: string) => {
    switch (level) {
      case 'Critical':
        return {
          bg: "bg-red-50/50 border-red-200",
          text: "text-red-600",
          bar: "bg-red-600",
          icon: <ShieldAlert className="w-6 h-6 text-red-600" />,
          title: "Critical Intervention Required"
        };
      case 'Warning':
        return {
          bg: "bg-orange-50/50 border-orange-200",
          text: "text-orange-600",
          bar: "bg-orange-600",
          icon: <AlertCircle className="w-6 h-6 text-orange-600" />,
          title: "Adherence Warning"
        };
      default:
        return {
          bg: "bg-blue-50/50 border-blue-200",
          text: "text-primary",
          bar: "bg-primary",
          icon: <CheckCircle2 className="w-6 h-6 text-primary" />,
          title: "System Stable"
        };
    }
  };

  // ✅ NEW: Dynamic Hex Colors for the Chart
  const getChartColor = (level: string) => {
    if (level === 'Critical') return '#dc2626'; // tailwind red-600
    if (level === 'Warning') return '#ea580c';  // tailwind orange-600
    return '#2563eb';                           // tailwind blue-600
  };

  // ✅ NEW: Dynamic Labels for the Trend Card
  const getTrendLabel = (level: string) => {
    if (level === 'Critical') return { text: 'Severe Risk', color: 'text-red-600' };
    if (level === 'Warning') return { text: 'At Risk', color: 'text-orange-600' };
    return { text: 'Healthy Pattern', color: 'text-success' };
  };

  const handleShareReport = async () => {
    if (!aiInsights) return;
  
    const reportDate = new Date().toLocaleDateString();
    const reportText = `📋 MediPredict Health Report (${reportDate}):\n-----------------------------------\n✅ Adherence Score: ${aiInsights.score}%\n⚠️ Risk Level: ${aiInsights.level}\n💡 AI Insight: ${aiInsights.insight}\n-----------------------------------\nGenerated by MediPredict AI Engine.`;
  
    if (navigator.share) {
      try {
        await navigator.share({ title: 'MediPredict Health Report', text: reportText });
      } catch (err) {
        console.log('Share cancelled or failed:', err);
      }
    } else {
      try {
        await navigator.clipboard.writeText(reportText);
        alert('Report copied to clipboard! Share it manually via email or message.');
      } catch (err) {
        console.error('Failed to copy report:', err);
      }
    }
  };

  const currentLevel = aiInsights?.level || 'Stable';
  const risk = getRiskStyles(currentLevel);
  const chartColor = getChartColor(currentLevel);
  const trendConfig = getTrendLabel(currentLevel);

  if (isLoading) return <div className="p-10 text-center font-bold text-primary animate-pulse">Syncing AI Models...</div>;

  return (
    <div className="space-y-6 mt-4 pb-20 animate-in fade-in duration-500">
      <header className="px-1">
        <h1 className="text-3xl font-extrabold text-text-primary font-display tracking-tight">Insights</h1>
        <p className="text-text-secondary font-medium">Real-time health trends and behavioral predictions</p>
      </header>

      {/* 🧠 Live AI Risk Prediction Card */}
      <motion.section 
        initial={{ y: -10, opacity: 0 }}
        animate={{ y: 0, opacity: 1 }}
        className={cn(
          "relative overflow-hidden rounded-[32px] border p-6 flex gap-5 items-start shadow-sm transition-colors duration-500",
          risk.bg
        )}
      >
        <div className="flex-shrink-0 w-14 h-14 rounded-2xl bg-white flex items-center justify-center shadow-sm">
          {risk.icon}
        </div>
        <div className="flex-grow space-y-2">
          <div className="flex items-center justify-between">
            <h3 className={cn("text-lg font-bold", risk.text)}>{risk.title}</h3>
            
            <div className="flex items-center gap-1.5 bg-white/80 backdrop-blur-sm px-3 py-1 rounded-full border border-black/5 shadow-sm">
              <span className="text-[10px] font-black text-text-secondary uppercase tracking-widest">Confidence</span>
              <span className={cn("text-xs font-black", risk.text)}>{aiInsights?.confidence || 0}%</span>
            </div>
          </div>
          <p className="text-sm text-gray-700 leading-relaxed font-medium">
            {aiInsights?.insight || "Your adherence pattern is currently within optimal parameters."}
          </p>
        </div>
      </motion.section>

      {/* 📊 Main Bento Grid */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        
        {/* Large Trend Card */}
        <section className={cn(
          "md:col-span-2 bg-white rounded-[32px] p-8 soft-shadow border flex flex-col gap-6 transition-colors duration-500",
          currentLevel === 'Critical' ? "border-red-100" : currentLevel === 'Warning' ? "border-orange-100" : "border-gray-50"
        )}>
          <div className="flex justify-between items-start">
            <div>
              <h2 className="text-sm font-bold text-text-secondary uppercase tracking-widest flex items-center gap-2">
                <Activity className="w-4 h-4" /> Adherence Trends
              </h2>
              <p className="text-xs text-gray-400 font-medium">Historical consistency analysis</p>
            </div>
            <div className="text-right">
              {/* ✅ FIX: Dynamic Color for 35% */}
              <span className={cn("text-4xl font-black font-display leading-none transition-colors", risk.text)}>
                {aiInsights?.score || 0}%
              </span>
              {/* ✅ FIX: Dynamic "Healthy Pattern" / "Severe Risk" label */}
              <p className={cn("text-[10px] font-black uppercase tracking-wider mt-1 transition-colors", trendConfig.color)}>
                {trendConfig.text}
              </p>
            </div>
          </div>

          <div className="h-56 w-full">
            <ResponsiveContainer width="100%" height="100%">
              <AreaChart data={trendData}>
                <defs>
                  <linearGradient id="colorRate" x1="0" y1="0" x2="0" y2="1">
                    {/* ✅ FIX: Dynamic Gradient Color */}
                    <stop offset="5%" stopColor={chartColor} stopOpacity={0.25}/>
                    <stop offset="95%" stopColor={chartColor} stopOpacity={0}/>
                  </linearGradient>
                </defs>
                <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#f8fafc" />
                <XAxis 
                  dataKey="day" 
                  axisLine={false} 
                  tickLine={false} 
                  tick={{fontSize: 10, fontWeight: 700, fill: '#94a3b8'}} 
                  dy={10}
                />
                <YAxis hide domain={[0, 100]} />
                <Tooltip 
                  cursor={{ stroke: '#e2e8f0', strokeWidth: 2 }}
                  contentStyle={{ borderRadius: '16px', border: 'none', boxShadow: '0 10px 15px -3px rgba(0,0,0,0.1)' }}
                  formatter={(value: number) => [`${value}%`, 'Adherence']}
                />
                <Area 
                  type="monotone" 
                  dataKey="rate" 
                  stroke={chartColor} // ✅ FIX: Dynamic Line Color
                  strokeWidth={4} 
                  fillOpacity={1} 
                  fill="url(#colorRate)" 
                  animationDuration={1500}
                />
              </AreaChart>
            </ResponsiveContainer>
          </div>
        </section>

        {/* Small Metric Stack */}
        <div className="flex flex-col gap-6">
          {/* ✅ FIX: Dynamic Consistency Score Card */}
          <section className={cn(
            "bg-white rounded-[32px] p-6 soft-shadow border flex-1 flex flex-col justify-between group transition-colors duration-500",
            currentLevel === 'Critical' ? "border-red-100" : currentLevel === 'Warning' ? "border-orange-100" : "border-gray-50"
          )}>
            <div className={cn(
              "w-12 h-12 rounded-2xl flex items-center justify-center transition-transform group-hover:scale-110",
              currentLevel === 'Critical' ? "bg-red-50 text-red-600" : 
              currentLevel === 'Warning' ? "bg-orange-50 text-orange-600" : "bg-blue-50 text-primary"
            )}>
              <Pill className="w-6 h-6" />
            </div>
            <div>
              <h4 className="text-[10px] font-bold text-text-secondary uppercase tracking-widest mb-1">Consistency Score</h4>
              <p className={cn("text-3xl font-black transition-colors", risk.text)}>
                {aiInsights?.score || '0'} <span className="text-sm text-gray-400 font-bold">/ 100</span>
              </p>
            </div>
          </section>

          <section className={cn(
            "rounded-[32px] p-6 soft-shadow border flex-1 flex flex-col justify-between transition-all duration-500",
            currentLevel === 'Warning' ? "bg-orange-50/30 border-orange-100" : 
            currentLevel === 'Critical' ? "bg-red-50/30 border-red-100" : "bg-white border-gray-50"
          )}>
            <div className={cn(
              "w-12 h-12 rounded-2xl flex items-center justify-center",
              currentLevel === 'Warning' ? "bg-orange-100 text-orange-600" : 
              currentLevel === 'Critical' ? "bg-red-100 text-red-600" : "bg-green-50 text-success"
            )}>
              <Timer className="w-6 h-6" />
            </div>
            <div className="space-y-2">
              <h4 className="text-[10px] font-bold text-text-secondary uppercase tracking-widest mb-1">Risk Level</h4>
              <p className={cn("text-3xl font-black", risk.text)}>
                {currentLevel}
              </p>
              
              <div className="space-y-1 mt-2">
                <div className="flex justify-between items-center text-[9px] font-black text-gray-400 uppercase tracking-tighter">
                  <span>ML Certainty</span>
                  <span>{aiInsights?.confidence ?? 0}%</span>
                </div>
                <div className="h-1.5 w-full bg-gray-100 rounded-full overflow-hidden">
                  <motion.div 
                    key={aiInsights?.confidence} 
                    initial={{ width: 0 }}
                    animate={{ width: `${aiInsights?.confidence ?? 0}%` }}
                    transition={{ duration: 1.2, ease: "easeOut" }}
                    className={cn("h-full transition-colors duration-500", risk.bar)} 
                  />
                </div>
              </div>
            </div>
          </section>
        </div>
      </div>

      {/* AI Advisory Section */}
      <section className="space-y-4">
        <h3 className="text-xl font-bold text-text-primary px-1">AI Health Advisory</h3>
        <div className={cn(
          "bg-white rounded-[32px] p-6 soft-shadow border flex gap-5 items-center transition-colors duration-500",
          currentLevel === 'Critical' ? "border-red-100" : currentLevel === 'Warning' ? "border-orange-100" : "border-gray-50"
        )}>
          {/* ✅ FIX: Dynamic Lightbulb Icon */}
          <div className={cn(
            "w-14 h-14 rounded-full flex items-center justify-center flex-shrink-0 transition-colors",
            currentLevel === 'Critical' ? "bg-red-50 text-red-600" : 
            currentLevel === 'Warning' ? "bg-orange-50 text-orange-600" : "bg-primary/10 text-primary"
          )}>
              <Lightbulb className="w-7 h-7" />
          </div>
          <div className="space-y-1">
            <p className="text-sm text-text-primary font-bold leading-relaxed">
              {aiInsights?.insight || "Maintain your current pace to reach a 98% adherence rate by next week."}
            </p>
            <p className={cn(
              "text-[10px] font-black uppercase tracking-widest flex items-center gap-1.5",
              risk.text
            )}>
              <BrainCircuit className="w-3.5 h-3.5" /> Predictive ML Analysis
            </p>
          </div>
        </div>

        <button 
        onClick={handleShareReport}
        className="w-full bg-white rounded-[24px] p-5 border border-gray-100 soft-shadow flex items-center justify-between hover:bg-gray-50 transition-all active:scale-[0.98]">
          <div className="flex items-center gap-4">
            <div className="w-10 h-10 rounded-full bg-gray-50 flex items-center justify-center text-gray-400">
              <Share2 className="w-5 h-5" />
            </div>
            <div className="text-left">
              <p className="text-sm font-bold text-text-primary">Share Report</p>
              <p className="text-xs text-text-secondary">Send live trends to your healthcare provider</p>
            </div>
          </div>
          <ChevronRight className="w-5 h-5 text-gray-300" />
        </button>
      </section>
    </div>
  );
};

export default PatientInsights;